/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensisekolah.view.GurudanStaff;

import absensisekolah.Dao.AbsensiGurudanStaffDao;
import absensisekolah.TableModel.AbsensiGurudanStaffTableModel;
import absensisekolah.view.AbsensiFrame;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JTable;

/**
 *
 * @author Conite
 */
public class AbsensiStaff extends javax.swing.JInternalFrame {

    AbsensiGurudanStaffDao AbsGrStDao ;
    
    
    public AbsensiStaff(AbsensiFrame AbsFrame) {
//        AbsGrStDao = new AbsensiGurudanStaffDao() ;
        initComponents();
        setSize(AbsFrame.getDeskPane().getSize());
//        TableStaff.setModel(new AbsensiGurudanStaffTableModel(AbsGrStDao.getListAbsSiswa()));
        TableStaff.setSize(getContentPane().getSize());
        setVisible(true);

    }

    public JTable getTableStaff() {
        return TableStaff;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableStaff = new javax.swing.JTable();

        setTitle("Absensi Staff");

        TableStaff.setAutoCreateRowSorter(true);
        TableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableStaff.setRowHeight(22);
        TableStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(TableStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStaff;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
