/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensisekolah.view.GurudanStaff;

import absensisekolah.Dao.GurudanStaffDao;
import absensisekolah.controler.GuruStaffControler;
import absensisekolah.view.GurudanStaff.*;
import absensisekolah.view.MainFrame;
import absensisekolah.view.Siswa.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class DataGurudanStaff extends javax.swing.JInternalFrame implements ListSelectionListener {

    int idGrSt;
    int Selection = -1;
    GuruViewDetail GVD;
    MainFrame Mf;
    ActionListener Al;
    GurudanStaffDao dao ;
    GuruStaffControler con ;

    public DataGurudanStaff(MainFrame Mf) {
        this.Mf = Mf;
        initComponents();
        setSize(Mf.getMainPane().getSize());
        TableDG.getSelectionModel().addListSelectionListener(this);
        byNm.setSelected(true);
        byJbtnField.setEnabled(false);
        dao = new GurudanStaffDao() ;
        con = new GuruStaffControler(dao, this) ;

    }

    public JTable getTableDG() {
        return TableDG;
    }

    public int getIdGrSt() {
        return idGrSt;
    }

    public JTextField getByJbtnField() {
        return byJbtnField;
    }

    public JTextField getByNmField() {
        return byNmField;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableDG = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        byNmField = new javax.swing.JTextField();
        byJbtnField = new javax.swing.JTextField();
        byNm = new javax.swing.JRadioButton();
        byJbtn = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Data Guru dan Staff");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/businessman.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(400, 400));
        setRequestFocusEnabled(false);
        setVisible(true);

        TableDG.setAutoCreateRowSorter(true);
        TableDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        TableDG.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableDG);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/businessman62x62.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Guru dan Staff");
        jLabel10.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Daftar Data");
        jLabel8.setToolTipText("");

        jLabel12.setText("data - data lengkap tentang guru dan staff");

        byNmField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                byNmFieldKeyPressed(evt);
            }
        });

        byJbtnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                byJbtnFieldKeyPressed(evt);
            }
        });

        byNm.setText("Pencarian Nama");
        byNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNmActionPerformed(evt);
            }
        });

        byJbtn.setText("Pencarian Jabatan");
        byJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(byJbtn)
                    .addComponent(byNm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(byJbtnField)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byNm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byJbtnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byJbtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void byNmFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byNmFieldKeyPressed

        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
            con.findList();
        }

    }//GEN-LAST:event_byNmFieldKeyPressed

    private void byJbtnFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byJbtnFieldKeyPressed
        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
            con.findList();
        }

    }//GEN-LAST:event_byJbtnFieldKeyPressed

    private void byNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNmActionPerformed
        if (byNm.isSelected())
        {
            byJbtn.setSelected(false);
            byJbtnField.setEnabled(false);
            byNmField.setEnabled(true);

        }

        if (byJbtn.isSelected()== false)
        {
            byNm.setSelected(true);
        }

    }//GEN-LAST:event_byNmActionPerformed

    private void byJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byJbtnActionPerformed
        if (byJbtn.isSelected())
        {
            byNm.setSelected(false);
            byNmField.setEnabled(false);
            byJbtnField.setEnabled(true);

        }

        if (byNm.isSelected()== false)
        {
            byJbtn.setSelected(true);

        }

    }//GEN-LAST:event_byJbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDG;
    private javax.swing.JRadioButton byJbtn;
    private javax.swing.JTextField byJbtnField;
    private javax.swing.JRadioButton byNm;
    private javax.swing.JTextField byNmField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent lse) {

        try {

            idGrSt = Integer.valueOf(TableDG.getValueAt(TableDG.getSelectedRow(), 0).toString());

        } catch (Exception ex) {
        }

    }
}
