/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absensisekolah.view.Siswa;

import absensisekolah.Dao.AbsensiSiswaDao;
import absensisekolah.Entity.AbsensiSiswaView;
import absensisekolah.TableModel.AbsensiSiswaTableModel;
import absensisekolah.view.AbsensiFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Conite
 */
public class AbsensiSiswa extends javax.swing.JInternalFrame  implements ListSelectionListener {

    AbsensiSiswaDao AbsSiswaDao ;
    AbsensiFrame AbsFrame ;
    private Integer idSiswa;
    
    
    public AbsensiSiswa(AbsensiFrame AbsFrame) {
        this.AbsFrame = AbsFrame ;
        AbsSiswaDao = new AbsensiSiswaDao () ;
        initComponents();
        setSize(AbsFrame.getDeskPane().getSize());     
        TableSiswa.setModel(new AbsensiSiswaTableModel (AbsSiswaDao.getListAbsSiswaTDY()));
        TableSiswa.getSelectionModel().addListSelectionListener(this);
        setVisible(true);
        
        
        
        
    }

    public JTable getTableSiswa() {
        return TableSiswa;
    }

    public Integer getIdSiswa() {
        return idSiswa;
    }
    
   
    
    
    
    
    public final void setTableView ()
    {
        int [] lbrTable = {260, 80, 80, 120} ;
        for (int i = 0; i<4; i++)
        {
            TableSiswa.getColumnModel().getColumn(i).setPreferredWidth(lbrTable[i]);
        }
        centerCellRenderer.setHorizontalAlignment(JLabel.CENTER);
        rightCellRenderer.setHorizontalAlignment(JLabel.RIGHT);
//        TableSiswa.getColumnModel().getColumn(5).setCellRenderer(centerCellRenderer);
//        TableSiswa.getColumnModel().getColumn(9).setCellRenderer(centerCellRenderer);
//        TableSiswa.getColumnModel().getColumn(10).setCellRenderer(centerCellRenderer);
//   
       }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableSiswa = new javax.swing.JTable();

        setTitle("Absensi Siswa");

        TableSiswa.setAutoCreateRowSorter(true);
        TableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableSiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableSiswa.setRowHeight(22);
        TableSiswa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(TableSiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSiswa;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    DefaultTableCellRenderer centerCellRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer rightCellRenderer = new DefaultTableCellRenderer();

    @Override
    public void valueChanged(ListSelectionEvent lse) {
           try {
                 
               idSiswa = Integer.valueOf(TableSiswa.getValueAt(TableSiswa.getSelectedRow(), 0).toString());
           } catch (Exception ex) {}
       
    }
    

}
