/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absensisekolah.view.Siswa;

import absensisekolah.Dao.SiswaDao;
import absensisekolah.controler.SiswaControler;
import absensisekolah.view.GurudanStaff.*;
import absensisekolah.view.MainFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Conite 
 */
public class DataSiswa extends javax.swing.JInternalFrame implements ListSelectionListener {
    
     ActionListener Al;
     MainFrame  Mf ;
     SiswaViewDetail SVD ;
     String Selection;
     int idSiswa;

     SiswaDao dao ;
     SiswaControler con ;
     
    /**
     * Creates new form AbsensiGuru
     */
    public DataSiswa(MainFrame Mf) {
        this.Mf = Mf ;
        initComponents();
        setSize(Mf.getMainPane().getSize());
      //  setAction();
        TableDataSiswa.getSelectionModel().addListSelectionListener(this);
        byNm.setSelected(true);
        byKelJurField.setEnabled(false);
        
        dao = new SiswaDao() ;
        con = new SiswaControler(dao, this) ;
        
        
    }

    public int getIdSiswa() {
        return idSiswa;
    }

    
    
    public JTable getTableDS() {
        return TableDataSiswa;
    }

    public JTextField getByKelJurField() {
        return byKelJurField;
    }

    public JTextField getByNmField() {
        return byNmField;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableDataSiswa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        byNmField = new javax.swing.JTextField();
        byKelJurField = new javax.swing.JTextField();
        byNm = new javax.swing.JRadioButton();
        byKel = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Data Siswa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/businessman.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(400, 400));
        setVisible(true);

        TableDataSiswa.setAutoCreateRowSorter(true);
        TableDataSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        TableDataSiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableDataSiswa);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Daftar Data");
        jLabel8.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Siswa");
        jLabel10.setToolTipText("");

        jLabel12.setText("data - data lengkap tentang siswa");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/user64x64.png"))); // NOI18N

        byNmField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                byNmFieldKeyPressed(evt);
            }
        });

        byKelJurField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                byKelJurFieldKeyPressed(evt);
            }
        });

        byNm.setText("Pencarian Nama");
        byNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNmActionPerformed(evt);
            }
        });

        byKel.setText("Pencarian Kel/ Jur");
        byKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byKelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(byKel)
                    .addComponent(byNm))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(byKelJurField)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byNm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byKelJurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byKel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void byNmFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byNmFieldKeyPressed

        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
            con.findList();
        }

    }//GEN-LAST:event_byNmFieldKeyPressed

    private void byKelJurFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byKelJurFieldKeyPressed
        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
            con.findList();
        }

    }//GEN-LAST:event_byKelJurFieldKeyPressed

    private void byNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNmActionPerformed
        if (byNm.isSelected())
        {
            byKel.setSelected(false);
            byKelJurField.setEnabled(false);
            byNmField.setEnabled(true);

        }

        if (byKel.isSelected()== false)
        {
            byNm.setSelected(true);
        }

    }//GEN-LAST:event_byNmActionPerformed

    private void byKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byKelActionPerformed
        if (byKel.isSelected())
        {
            byNm.setSelected(false);
            byNmField.setEnabled(false);
            byKelJurField.setEnabled(true);

        }

        if (byNm.isSelected()== false)
        {
            byKel.setSelected(true);

        }

    }//GEN-LAST:event_byKelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDataSiswa;
    private javax.swing.JRadioButton byKel;
    private javax.swing.JTextField byKelJurField;
    private javax.swing.JRadioButton byNm;
    private javax.swing.JTextField byNmField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent lse) {
           try {
                 
               idSiswa = Integer.valueOf(TableDataSiswa.getValueAt(TableDataSiswa.getSelectedRow(), 0).toString());
           } catch (Exception ex) {}
       
    }
}
