/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package absensisekolah.view.Siswa;

import absensisekolah.Dao.AbsensiSiswaDao;
import absensisekolah.TableModel.DASTableModel;
import absensisekolah.controler.AbsensiSiswaControler;
import absensisekolah.view.GurudanStaff.*;
import absensisekolah.view.MainFrame;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Conite 
 */
public class DataAbsensiSiswa extends javax.swing.JInternalFrame  implements ListSelectionListener {

    MainFrame Mf ;
    private int idSiswa;
    AbsensiSiswaControler controler ;
    AbsensiSiswaDao AbsSswDao ;
    
    public DataAbsensiSiswa(MainFrame Mf) {
        this.Mf = Mf ;
        initComponents();
        setSize(Mf.getMainPane().getSize());
        TableDAS.getSelectionModel().addListSelectionListener(this);
        controler = new AbsensiSiswaControler(this, new AbsensiSiswaDao()) ;
        byNm.setSelected(true);
        bydtField.setEnabled(false);
        
        
    }

    public JTable getTableDAS() {
        return TableDAS;
    }

    public Integer getIdSiswa() {
        return idSiswa;
    }

    public JTextField getByNmField() {
        return byNmField;
    }

    public JTextField getBydtField() {
        return bydtField;
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableDAS = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        byNmField = new javax.swing.JTextField();
        bydtField = new javax.swing.JTextField();
        byNm = new javax.swing.JRadioButton();
        byDt = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Data Absensi Siswa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/businessman.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(400, 400));
        setVisible(true);

        TableDAS.setAutoCreateRowSorter(true);
        TableDAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TableDAS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableDAS);

        byNmField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                byNmFieldKeyPressed(evt);
            }
        });

        bydtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bydtFieldKeyPressed(evt);
            }
        });

        byNm.setText("Pencarian Nama");
        byNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNmActionPerformed(evt);
            }
        });

        byDt.setText("Pencarian Tanggal");
        byDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byDtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(byDt)
                    .addComponent(byNm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bydtField)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byNmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byNm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bydtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byDt))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Daftar Data Absensi");
        jLabel8.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Siswa");
        jLabel10.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensisekolah/Img/user64x64.png"))); // NOI18N

        jLabel12.setText("data - data lengkap tentang absensi siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void byNmFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_byNmFieldKeyPressed
       
        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
            controler.findList();
        }
        
    }//GEN-LAST:event_byNmFieldKeyPressed

    private void byNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNmActionPerformed
       if (byNm.isSelected())
       {
           byDt.setSelected(false);
           bydtField.setEnabled(false);
           byNmField.setEnabled(true);
           
           
       }
           
       if (byDt.isSelected()== false)
       {
           byNm.setSelected(true);
       }    
        
    }//GEN-LAST:event_byNmActionPerformed

    private void byDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byDtActionPerformed
        if (byDt.isSelected())
       {
           byNm.setSelected(false);
           byNmField.setEnabled(false);
           bydtField.setEnabled(true);
          
       }
           
       if (byNm.isSelected()== false)
       {
           byDt.setSelected(true);
          
       }    
        
    }//GEN-LAST:event_byDtActionPerformed

    private void bydtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bydtFieldKeyPressed
        int ev = evt.getKeyCode() ;
        if ( ev == KeyEvent.VK_ENTER)
        {
        controler.findList();
        }
        
    }//GEN-LAST:event_bydtFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDAS;
    private javax.swing.JRadioButton byDt;
    private javax.swing.JRadioButton byNm;
    private javax.swing.JTextField byNmField;
    private javax.swing.JTextField bydtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent lse) {
           try {
                    idSiswa = Integer.valueOf(TableDAS.getValueAt(TableDAS.getSelectedRow(), 0).toString());
           }    
           catch (Exception ex) 
           {
            
           } 
    }


}
